suppressWarnings(pkgload::load_all("."), quiet=TRUE))
d <- simulate_rasch(2000, 20, dif = list(items = "I06", uniform = 0.7),
                     n_groups = 2, seed = 1)
tr <- attr(d, "truth")
str(tr, max.level=1)
cat("delta I06:", tr$delta["I06"], "\n")
cat("dif uniform:", tr$dif$uniform, "\n")
fit <- rasch(d, id="id", factors="group")
ds <- dif_size(fit, "I06", by="group")
print(ds$levels)
print(ds$pairs)
