suppressWarnings(pkgload::load_all(".", quiet=TRUE))
t0 <- Sys.time()
d <- simulate_rasch(500, 20, n_groups = 2, seed = 1)
fit <- rasch(d, id = "id", factors = "group")
t1 <- Sys.time()
da <- dif_anova(fit)
t2 <- Sys.time()
cat("fit time:", as.numeric(t1-t0,units="secs"), "\n")
cat("dif_anova time:", as.numeric(t2-t1,units="secs"), "\n")
