suppressWarnings(pkgload::load_all(".", quiet=TRUE))
d <- simulate_rasch(500, 20, n_groups = 2, missing = 0.25, seed = 999)
t0 <- Sys.time()
fit <- rasch(d, id = "id", factors = "group")
t1 <- Sys.time()
cat("fit time:", as.numeric(t1-t0,units="secs"), "\n")
cat("iterations:", fit$est$iterations, "\n")
str(fit$est[c("iterations","converged")])
