suppressWarnings(pkgload::load_all(".", quiet=TRUE))
source("tools/simval/round1/dif/gen_repeated.R")
long <- gen_repeated(N=300, n_items=8, g_levels=1, occ_levels=2, occ_dif_item=4, occ_dif_shift=0.7, seed=1)
str(long)
item_cols <- sprintf("I%02d", 1:8)
stacked <- stack_data(long, person="person", time="occasion", items=item_cols)
str(stacked)
fit <- rasch(stacked, id="id", factors="time")
da <- dif_anova(fit, within="time")
print(da$summary)
