suppressWarnings(pkgload::load_all(".", quiet=TRUE))
t0 <- Sys.time()
d <- simulate_rasch(500, 15, difficulty=c(-2,2), seed=1)
fit <- rasch(d, id="id")
t1 <- Sys.time()
cat("fit time:", as.numeric(t1-t0,units="secs"), "s\n")
str(attr(d,"truth"), max.level=1)
print(names(fit))
print(head(fit$items))
print(head(fit$person))
