suppressWarnings(pkgload::load_all(".", quiet=TRUE))
d <- simulate_rasch(300, 10, difficulty=c(-2,2), seed=1)
f <- rasch(d, id="id")
r <- sim_recovery(f, d)
print(r$summary)
print(str(attr(d,"truth")$theta))
print(str(attr(d,"truth")$difficulty))
st <- score_table(f, extremes="extrapolated")
print(st)
