suppressWarnings(pkgload::load_all(".", quiet=TRUE))
set.seed(1)
t0<-Sys.time()
d <- simulate_btl(n_objects=6, n_judges=12, reps_per_pair=40, seed=1)
f <- btl(d, "object_a","object_b", winner="winner", judge="judge")
grp <- setNames(rep(c("g1","g2"), each=6), sprintf("J%d", 1:12))
dif <- btl_dif(f, grp)
t1<-Sys.time()
cat("time:", as.numeric(t1-t0,units="secs"), "\n")
print(dif$summary)
