suppressWarnings(pkgload::load_all(".", quiet=TRUE))
set.seed(123)
d <- simulate_btl(n_objects=15, n_judges=20, reps_per_pair=60,
                   second_attribute=list(rho=0.0), object_sd=1.5, seed=123)
f <- btl(d, "object_a","object_b", winner="winner", judge="judge")
bd <- btl_dimensionality(f, reps=150)
print(bd$bimensions)
cat("leading_structured:", bd$leading_structured, "\n")
tr <- attr(d,"truth")
cat("cor(location,location2):", cor(tr$location, tr$location2), "\n")
cat("total_p (unidim fit):", f$total_p, " total_chisq/df:", f$total_chisq/f$total_df, "\n")
