suppressWarnings(pkgload::load_all(".", quiet=TRUE))
set.seed(1)
d <- simulate_efrm(300, 8, n_sets=2, n_groups=2, set_unit_ratio=1.3, group_unit_ratio=1.2, seed=1)
tr <- attr(d,"truth")
fit <- rasch_efrm(d, item_sets=tr$item_sets, groups="group", se_method="hybrid")
cat("person head:\n"); print(head(fit$person))
cat("nrow person vs d:", nrow(fit$person), nrow(d), "\n")
cat("id match order check (first 5 ids):\n")
print(head(fit$person$id)); print(head(d$id))
cat("item_arbitrary:\n"); print(fit$item_arbitrary)
cat("truth difficulty:\n"); print(tr$difficulty)
cat("thresholds_arbitrary head:\n"); print(head(fit$thresholds_arbitrary,20))
cat("frames:\n"); print(fit$frames)
