suppressWarnings(pkgload::load_all("."), quiet=TRUE))
set.seed(1)
d <- simulate_efrm(300, 8, n_sets=2, n_groups=2, set_unit_ratio=1.3, group_unit_ratio=1, seed=1)
t1 <- system.time(fit <- rasch_efrm(d, item_sets=attr(d,"truth")$item_sets, groups="group", se_method="hybrid"))
print(t1)
t2 <- system.time(fit2 <- rasch_efrm(d, item_sets=attr(d,"truth")$item_sets, groups="group", se_method="bootstrap", boot_reps=100))
print(t2)
cat("alpha_table:\n"); print(fit$alpha_table)
cat("phi_table:\n"); print(fit$phi_table)
cat("names:\n"); print(names(fit))
