// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// efrm_likelihood_cpp
NumericMatrix efrm_likelihood_cpp(NumericVector u, LogicalMatrix obs, NumericVector score, List taus, NumericVector discs);
RcppExport SEXP _rasch_efrm_likelihood_cpp(SEXP uSEXP, SEXP obsSEXP, SEXP scoreSEXP, SEXP tausSEXP, SEXP discsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type u(uSEXP);
    Rcpp::traits::input_parameter< LogicalMatrix >::type obs(obsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type score(scoreSEXP);
    Rcpp::traits::input_parameter< List >::type taus(tausSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type discs(discsSEXP);
    rcpp_result_gen = Rcpp::wrap(efrm_likelihood_cpp(u, obs, score, taus, discs));
    return rcpp_result_gen;
END_RCPP
}
// efrm_fit_weights_cpp
List efrm_fit_weights_cpp(NumericMatrix L, NumericMatrix logw, IntegerVector mix_idx, NumericVector count, int maxit, double tol);
RcppExport SEXP _rasch_efrm_fit_weights_cpp(SEXP LSEXP, SEXP logwSEXP, SEXP mix_idxSEXP, SEXP countSEXP, SEXP maxitSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type L(LSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type logw(logwSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type mix_idx(mix_idxSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type count(countSEXP);
    Rcpp::traits::input_parameter< int >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(efrm_fit_weights_cpp(L, logw, mix_idx, count, maxit, tol));
    return rcpp_result_gen;
END_RCPP
}
// efrm_negloglik_cpp
double efrm_negloglik_cpp(NumericVector z, NumericVector grid, LogicalMatrix obs, NumericVector score, List taus, NumericVector discs, NumericMatrix La, NumericMatrix logw, IntegerVector mix_idx, NumericVector count);
RcppExport SEXP _rasch_efrm_negloglik_cpp(SEXP zSEXP, SEXP gridSEXP, SEXP obsSEXP, SEXP scoreSEXP, SEXP tausSEXP, SEXP discsSEXP, SEXP LaSEXP, SEXP logwSEXP, SEXP mix_idxSEXP, SEXP countSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type z(zSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type grid(gridSEXP);
    Rcpp::traits::input_parameter< LogicalMatrix >::type obs(obsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type score(scoreSEXP);
    Rcpp::traits::input_parameter< List >::type taus(tausSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type discs(discsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type La(LaSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type logw(logwSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type mix_idx(mix_idxSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type count(countSEXP);
    rcpp_result_gen = Rcpp::wrap(efrm_negloglik_cpp(z, grid, obs, score, taus, discs, La, logw, mix_idx, count));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_rasch_efrm_likelihood_cpp", (DL_FUNC) &_rasch_efrm_likelihood_cpp, 5},
    {"_rasch_efrm_fit_weights_cpp", (DL_FUNC) &_rasch_efrm_fit_weights_cpp, 6},
    {"_rasch_efrm_negloglik_cpp", (DL_FUNC) &_rasch_efrm_negloglik_cpp, 10},
    {NULL, NULL, 0}
};

RcppExport void R_init_rasch(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
