# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

efrm_likelihood_cpp <- function(u, obs, score, taus, discs) {
    .Call(`_rasch_efrm_likelihood_cpp`, u, obs, score, taus, discs)
}

efrm_fit_weights_cpp <- function(L, logw, mix_idx, count, maxit = 100L, tol = 1e-7) {
    .Call(`_rasch_efrm_fit_weights_cpp`, L, logw, mix_idx, count, maxit, tol)
}

efrm_negloglik_cpp <- function(z, grid, obs, score, taus, discs, La, logw, mix_idx, count) {
    .Call(`_rasch_efrm_negloglik_cpp`, z, grid, obs, score, taus, discs, La, logw, mix_idx, count)
}
