suppressWarnings(pkgload::load_all("."), quiet=TRUE))
t0 <- Sys.time()
d <- simulate_mfrm(120, 6, 8, n_categories=4, rater_severity_sd=0.7, seed=1)
mf <- rasch_mfrm(d, person="person", item="item", score="score", facets="rater")
t1 <- Sys.time()
cat("fit time:", as.numeric(t1-t0, units="secs"), "s\n")
cat("n virtual items:", ncol(mf$X), " n persons:", nrow(mf$X), "\n")
print(cor(mf$facet_effects$rater$severity, attr(d,"truth")$severity))
print(cor(mf$item_effects$location, attr(d,"truth")$difficulty))
